#!/usr/bin/env python3
"""Regenerate corpus/manifest.yml.

    python3 tools/corpus_manifest.py [baseline-dir ...]

For every .phyphox file under corpus/, the manifest records the file format
version it declares and the spec constructs it exercises that no file in the
baseline does. The baseline is the shipped experiment collection; it defaults
to the Android checkout's copy, which is a sibling of this repository on the
development machines and has to be passed explicitly elsewhere.

The manifest is generated - edit this script or the corpus, not the YAML.
"""

import os
import sys
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CORPUS = os.path.join(ROOT, "corpus")
DEFAULT_BASELINE = os.path.join(
    ROOT, "..", "phyphox-android", "app", "src", "main", "assets", "experiments")

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from validate_experiments import normalize_namespace


def usage(base):
    pairs, attrs = set(), set()
    for dirpath, _, names in os.walk(base):
        for n in sorted(names):
            if not n.endswith(".phyphox"):
                continue
            try:
                root = normalize_namespace(
                    ET.parse(os.path.join(dirpath, n)).getroot())
            except ET.ParseError:
                continue
            yield os.path.relpath(os.path.join(dirpath, n), base), root


def constructs(root):
    pairs, attrs = set(), set()

    def walk(node, parent):
        pairs.add((parent, node.tag))
        for a in node.attrib:
            attrs.add((node.tag, a))
        for c in node:
            walk(c, node.tag)

    walk(root, "<root>")
    return pairs, attrs


def main():
    baselines = sys.argv[1:] or [DEFAULT_BASELINE]
    base_pairs, base_attrs = set(), set()
    for b in baselines:
        for _, root in usage(b):
            p, a = constructs(root)
            base_pairs |= p
            base_attrs |= a

    lines = ["# Generated by tools/corpus_manifest.py - do not edit.",
             "#",
             "# For each corpus file: the file format version it declares, and",
             "# the spec constructs it exercises that the shipped experiment",
             "# collection does not. An empty `adds` means the file is here for",
             "# a reason the construct list cannot show (a crash reproduction,",
             "# a systematic value sweep, a container form).",
             ""]
    for rel, root in sorted(usage(CORPUS)):
        p, a = constructs(root)
        adds = sorted(f"{parent}>{el}" for parent, el in p - base_pairs) + \
               sorted(f"{el}@{attr}" for el, attr in a - base_attrs)
        lines.append(f"- file: {rel}")
        lines.append(f"  version: \"{root.get('version')}\"")
        if adds:
            lines.append("  adds:")
            lines += [f"    - {x}" for x in adds]
        else:
            lines.append("  adds: []")
    out = os.path.join(CORPUS, "manifest.yml")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
