#!/usr/bin/env python3
"""Generate RELAX NG and Schematron validators from spec/*.yml.

    python3 tools/generate_validators.py [output-directory]

This is phase 4a: the machine-readable spec, which already generates the
reference pages, additionally generates validators in standard schema
languages so that anyone - not just this repository's Python tooling - can
check a .phyphox file. Three artifacts, written to docs/assets/validators/
(gitignored; they are build products, regenerated by tools/hooks.py on every
build and shipped with the site):

    phyphox.rng   RELAX NG, XML syntax - what lxml validates against in the
                  build's self-test
    phyphox.rnc   RELAX NG, compact syntax - the same grammar for humans;
                  both are emitted from one internal pattern tree, so they
                  cannot drift apart
    phyphox.sch   ISO Schematron - the rules a grammar cannot express

What the grammar covers and what it deliberately does not:

  * Element names are matched in every namespace seen in real files - none,
    http://phyphox.org/xml and https://phyphox.org/xml - via name-class
    choices. The apps' actual rule ("the format's namespace is whatever the
    root element declares") is not expressible in a fixed grammar; these
    three cover everything in circulation. A file mixing them would
    validate; the apps would accept it too.
  * Foreign-namespace elements are allowed (with any content) inside every
    element, and foreign-namespace attributes on every element, mirroring
    the documented rule that parsers ignore both - this is how
    editor-generated files carry editor:uuid and friends.
  * Every element is mixed content: the pull parsers skip text nodes they
    do not expect, and real files use that for inline notes ("<input/> 64
    times"), so stray text must not fail validation.
  * Numeric attribute values are checked by syntax (rules.yml,
    number-invalid-value): both apps reject the file when a present
    number does not parse.
  * Enumerated values, booleans and named colors are matched
    case-insensitively via generated XSD patterns (rules.yml,
    enum-case-insensitive). Tag case-insensitivity (tag-case-insensitive)
    is NOT expressible in RELAX NG: the grammar accepts the canonical
    lowercase spelling only.
  * Attribute sets are closed: an attribute the spec does not model fails
    validation, like in tools/validate_experiments.py. This is deliberately
    STRICTER than the apps, which silently ignore unknown attributes
    (rules.yml, unknown-attribute-ignored) - flagging the cycles= typo is
    the validators' job at authoring time. The one dynamically
    numbered family (mapColor[N]) is admitted through a wildcard, tightened
    back to the exact name shape by a Schematron rule.
  * Child-element counts are approximated: presence is enforced where a
    slot's min demands it, but exact upper bounds and per-slot minimums
    (which depend on the as attribute) are left to the apps and
    validate_experiments.

The Schematron carries, as errors: data-container references resolving
(analysis and view inputs/outputs, export data, input-module outputs, audio
output inputs, network send/receive), container name uniqueness, the graph
dataset pairing rules of 2026-08-20, and the mapColor[N] name shape. As
warnings (role="warning"): the since-version gates - an element or
attribute used below the file format version that introduced it, which the
apps tolerate but older apps will not.
"""

import os
import re
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPEC = os.path.join(ROOT, "spec")

# Lexical space of a number in the format (rules.yml, number-invalid-value):
# plain decimal notation, plus the special values NaN and +-Infinity matched
# case-insensitively (corpus files use init="NaN" as a deliberate gap marker
# for graphs, and init="nan" exists too). Deliberately narrower than
# xsd:double and than either platform's library parser - hexadecimal and
# suffixed forms, "inf", and localized decimal commas parse on one platform
# and not the other. tools/validate_experiments.py imports these so the
# Python checker and the grammar cannot disagree on what a number is.
FLOAT_LEX = (r"([+-]?([0-9]+(\.[0-9]*)?|\.[0-9]+)([eE][+-]?[0-9]+)?"
             r"|[nN][aA][nN]|[+-]?[iI][nN][fF][iI][nN][iI][tT][yY])")
INT_LEX = r"[+-]?[0-9]+"
FLOAT_LIST_LEX = r"(\s*" + FLOAT_LEX + r"(\s*,\s*" + FLOAT_LEX + r")*\s*)?"
DEFAULT_OUT = os.path.join(ROOT, "docs", "assets", "validators")

PHYPHOX_NS = "http://phyphox.org/xml"
# The apps ignore namespaces entirely and take whatever the root declares as
# the file's own namespace; a grammar cannot express that, but both URI
# spellings seen in real files are admitted alongside "no namespace".
PHYPHOX_NS_ALT = "https://phyphox.org/xml"
RNG_NS = "http://relaxng.org/ns/structure/1.0"
XSD = "http://www.w3.org/2001/XMLSchema-datatypes"


# ------------------------------------------------------------------ model --

def load():
    els, common, colors = {}, {}, []
    for fn in sorted(os.listdir(SPEC)):
        if not fn.endswith(".yml") or fn == "rules.yml":
            continue
        doc = yaml.safe_load(open(os.path.join(SPEC, fn), encoding="utf-8")) or {}
        block = doc.get("block") or fn[:-4]
        for group, items in (doc.get("common") or {}).items():
            common.setdefault(block, {})[group] = items or []
        for el in doc.get("elements") or []:
            els[(block, el.get("parent"), el["name"])] = el
        if doc.get("colors"):
            colors = [c["name"] for c in doc["colors"].get("names") or []]
    return els, common, colors


def resolve_child(els, block, parent_name, child):
    """(block, element, child-name) -> the child's element key."""
    key = (block, parent_name, child)
    if key in els:
        return key
    hits = [k for k in els if k[1] == parent_name and k[2] == child]
    if len(hits) == 1:
        return hits[0]
    raise KeyError(f"cannot resolve child <{child}> of <{parent_name}> "
                   f"in block {block}: {hits}")


# ------------------------------------------------------- pattern emitters --

def ci_pattern(value):
    """XSD regex accepting one literal case-insensitively."""
    return "".join(f"[{ch.lower()}{ch.upper()}]" if ch.isalpha()
                   else re.escape(ch) for ch in str(value))


def ci_choice(values):
    """A choice of one single-value pattern per literal.

    One big alternation would be the obvious encoding, but libxml2's regex
    determinization blows up on unions of long branches and hangs compiling
    the grammar; a choice of linear per-value patterns compiles instantly
    and matches the same language."""
    parts = [P("data", pattern=ci_pattern(v)) for v in values]
    return parts[0] if len(parts) == 1 else P("choice", parts=parts)


class P:
    """One node of the pattern tree; kind drives both emitters."""

    def __init__(self, kind, **kw):
        self.kind = kind
        self.__dict__.update(kw)


def attr_value_pattern(attr, colors):
    kind = attr.get("type")
    if kind == "enum":
        return ci_choice(attr.get("values") or [])
    if kind == "boolean":
        return ci_choice(["true", "false"])
    if kind == "integer":
        return P("data", pattern=INT_LEX)
    if kind == "float":
        return P("data", pattern=FLOAT_LEX)
    if kind == "float-list":
        return P("data", pattern=FLOAT_LIST_LEX)
    if kind == "color":
        return P("choice", parts=[P("data", pattern="#?[0-9a-fA-F]{6}")]
                 + [P("data", pattern=ci_pattern(c)) for c in colors])
    if attr.get("name") == "version":
        return P("data", pattern="[0-9]+\\.[0-9]+")
    return P("text")


VALUE_TYPES = {}


def value_ref(node):
    """Replace a value pattern by a ref to a shared define.

    The grammar uses the same few value types hundreds of times (65 boolean
    attributes alone); emitting each inline made libxml2's compile time
    explode. One define per distinct type keeps the artifact small and the
    compile fast."""
    if node.kind == "text":
        return node
    key = repr_node(node)
    if key not in VALUE_TYPES:
        VALUE_TYPES[key] = (f"vt.{len(VALUE_TYPES)}", node)
    return P("ref", name=VALUE_TYPES[key][0])


def repr_node(node):
    if node.kind == "data":
        return ("data", getattr(node, "xsd", None),
                getattr(node, "pattern", None))
    if node.kind == "choice":
        return ("choice", tuple(repr_node(p) for p in node.parts))
    return (node.kind,)


def element_pattern(els, common, colors, key):
    block, parent, name = key
    el = els[key]

    attrs = list(el.get("attributes") or [])
    # common groups: analysis modules and view elements. An element that
    # declares one of the common names itself (info's label is the displayed
    # text) keeps its own entry; declaring both would be an invalid grammar.
    own = {a["name"] for a in attrs}
    extra = []
    if parent == "analysis":
        extra = common.get("analysis", {}).get("module_attributes", [])
    if parent == "view":
        extra = common.get("views", {}).get("view_element_attributes", [])
    # Every io-style <input>/<output> element accepts the shared io
    # attributes (as/type/keep/clear resp. as/append/clear): Android parses
    # them all through the same ioBlockParser, and
    # tools/validate_experiments.py accepts them the same way - a button's
    # <output clear="false"> is legal, for example.
    if name == "input":
        extra = extra + common.get("analysis", {}).get("input_attributes", [])
    if name == "output":
        extra = extra + common.get("analysis", {}).get("output_attributes", [])
    seen = set(own)
    merged = []
    for a in extra:
        if a["name"] not in seen:
            merged.append(a)
            seen.add(a["name"])
    attrs += merged

    parts = []
    known_names = []
    wildcard_types = []
    for a in attrs:
        if a.get("name_pattern"):
            wildcard_types.append(attr_value_pattern(a, colors))
            continue
        known_names.append(a["name"])
        node = P("attribute", name=a["name"],
                 value=value_ref(attr_value_pattern(a, colors)))
        parts.append(node if a.get("required") else P("optional", child=node))
    if wildcard_types:
        # mapColor[N] and friends: any undeclared no-namespace attribute is
        # admitted here with the family's value type; the Schematron pins the
        # name down to the exact numbered shape.
        parts.append(P("zeroOrMore", child=P(
            "attribute_except", names=known_names,
            value=value_ref(wildcard_types[0]))))

    # The apps read attributes by their no-namespace name and ignore
    # everything else, so editor-generated files carry editor:uuid and
    # friends on almost every element. Admit any foreign-namespace
    # attribute everywhere.
    parts.append(P("ref", name="foreignAttrs"))

    # libxml2 validates a plain sequence of optional attributes by
    # backtracking - exponential once ~16 attributes are present on the
    # element (a fully specified <graph> has ~45). An explicit interleave
    # of the same patterns takes its optimized attribute-group path and
    # stays linear, with identical semantics (attributes are unordered
    # anyway), so every element wraps its attribute patterns in one.
    if len(parts) >= 2:
        parts = [P("interleave", parts=parts)]

    content = []

    def slot_children(slots, tag, group):
        cattrs = []
        slot_names = [s["name"] for s in slots]
        cattrs.append(P("optional", child=P(
            "attribute", name="as", value=value_ref(ci_choice(slot_names)))))
        for ca in common.get("analysis", {}).get(group, []):
            if ca["name"] == "as":
                continue
            cattrs.append(P("optional", child=P(
                "attribute", name=ca["name"],
                value=value_ref(attr_value_pattern(ca, colors)))))
        cattrs.append(P("ref", name="foreignAttrs"))
        node = P("element", names=[tag], parts=cattrs + [P("text")])
        need = sum(int(s.get("min") or 0) for s in slots)
        single = (len(slots) == 1 and slots[0].get("max") == 1)
        if single:
            return node if need else P("optional", child=node)
        return P("oneOrMore" if need else "zeroOrMore", child=node)

    if isinstance(el.get("inputs"), list):
        content.append(slot_children(el["inputs"], "input",
                                     "input_attributes"))
    if isinstance(el.get("outputs"), list):
        content.append(slot_children(el["outputs"], "output",
                                     "output_attributes"))
    if isinstance(el.get("outputs"), dict):
        mapping = el["outputs"]
        comp_attr = mapping.get("attribute", "component")
        names = [c["name"] for c in mapping.get("components") or []]
        cattr = P("attribute", name=comp_attr,
                  value=value_ref(ci_choice(names)))
        cparts = [cattr if mapping.get("required_component")
                  else P("optional", child=cattr)]
        for ca in common.get("analysis", {}).get("output_attributes", []):
            if ca["name"] in ("as", comp_attr):
                continue
            cparts.append(P("optional", child=P(
                "attribute", name=ca["name"],
                value=value_ref(attr_value_pattern(ca, colors)))))
        cparts.append(P("ref", name="foreignAttrs"))
        node = P("element", names=["output"], parts=cparts + [P("text")])
        need = any(c.get("required") for c in mapping.get("components") or [])
        content.append(P("oneOrMore" if need else "zeroOrMore", child=node))

    optional_kinds = [P("ref", name="foreign")]
    for child in el.get("children") or []:
        if child in ("input", "output") and (
                isinstance(el.get("inputs"), list)
                or isinstance(el.get("outputs"), (list, dict))):
            continue
        ckey = resolve_child(els, block, name, child)
        optional_kinds.append(P("ref", name=define_id(ckey)))

    if content or len(optional_kinds) > 1:
        # All-optional unordered children are one repeated choice rather
        # than an interleave: (a* & b* & ...) is equivalent to (a | b)*,
        # and libxml2's interleave computation blows up combinatorially on
        # wide interleaves like the analysis element's 54 modules.
        merged = P("zeroOrMore", child=(
            P("choice", parts=optional_kinds) if len(optional_kinds) > 1
            else optional_kinds[0]))
        # ... with a text operand: both pull parsers skip text nodes they
        # do not expect, so stray prose between children ("<input/> 64
        # times") loads fine and occurs in real files - every element with
        # children is mixed content.
        if content:
            parts.append(P("interleave",
                           parts=content + [merged, P("text")]))
        else:
            parts.append(P("interleave", parts=[merged, P("text")]))
    else:
        # childless elements tolerate stray text for the same reason
        parts.append(P("text"))

    return P("element", names=[name], parts=parts)


def define_id(key):
    block, parent, name = key
    return f"d.{block}.{parent or 'root'}.{name}".replace("-", "_")


# -------------------------------------------------------------- rng (xml) --

def rng_xml(defines, start_id):
    import xml.etree.ElementTree as ET
    ET.register_namespace("", RNG_NS)

    def q(tag):
        return f"{{{RNG_NS}}}{tag}"

    def name_class_elem(parent, names):
        choice = ET.SubElement(parent, q("choice"))
        for n in names:
            ET.SubElement(choice, q("name")).text = n
            for ns in (PHYPHOX_NS, PHYPHOX_NS_ALT):
                e = ET.SubElement(choice, q("name"))
                e.set("ns", ns)
                e.text = n

    def emit(node, parent):
        if node.kind == "element":
            e = ET.SubElement(parent, q("element"))
            name_class_elem(e, node.names)
            for p in node.parts:
                emit(p, e)
        elif node.kind == "attribute":
            e = ET.SubElement(parent, q("attribute"))
            e.set("name", node.name)
            emit(node.value, e)
        elif node.kind == "attribute_except":
            # no-namespace names only, so the class cannot overlap the
            # foreignAttrs wildcard in the same interleave (RELAX NG
            # forbids competing attribute name classes there)
            e = ET.SubElement(parent, q("attribute"))
            any_name = ET.SubElement(e, q("nsName"))
            any_name.set("ns", "")
            if node.names:
                exc = ET.SubElement(any_name, q("except"))
                for n in node.names:
                    nm = ET.SubElement(exc, q("name"))
                    nm.set("ns", "")
                    nm.text = n
            emit(node.value, e)
        elif node.kind in ("optional", "zeroOrMore", "oneOrMore"):
            e = ET.SubElement(parent, q(node.kind))
            emit(node.child, e)
        elif node.kind == "interleave":
            e = ET.SubElement(parent, q("interleave"))
            for p in node.parts:
                emit(p, e)
        elif node.kind == "choice":
            e = ET.SubElement(parent, q("choice"))
            for p in node.parts:
                emit(p, e)
        elif node.kind == "ref":
            ET.SubElement(parent, q("ref")).set("name", node.name)
        elif node.kind == "text":
            ET.SubElement(parent, q("text"))
        elif node.kind == "empty":
            ET.SubElement(parent, q("empty"))
        elif node.kind == "data":
            e = ET.SubElement(parent, q("data"))
            if getattr(node, "xsd", None):
                e.set("type", node.xsd)
            else:
                e.set("type", "string")
                p = ET.SubElement(e, q("param"))
                p.set("name", "pattern")
                p.text = node.pattern
        else:
            raise ValueError(node.kind)

    grammar = ET.Element(q("grammar"))
    grammar.set("datatypeLibrary", XSD)
    start = ET.SubElement(grammar, q("start"))
    ET.SubElement(start, q("ref")).set("name", start_id)

    for did, node in defines.items():
        d = ET.SubElement(grammar, q("define"))
        d.set("name", did)
        emit(node, d)

    # the foreign-element wildcard: any element outside both namespaces
    d = ET.SubElement(grammar, q("define"))
    d.set("name", "foreign")
    e = ET.SubElement(d, q("element"))
    any_name = ET.SubElement(e, q("anyName"))
    exc = ET.SubElement(any_name, q("except"))
    ET.SubElement(exc, q("nsName")).set("ns", "")
    ET.SubElement(exc, q("nsName")).set("ns", PHYPHOX_NS)
    ET.SubElement(exc, q("nsName")).set("ns", PHYPHOX_NS_ALT)
    ET.SubElement(e, q("ref")).set("name", "foreignInner")

    d = ET.SubElement(grammar, q("define"))
    d.set("name", "foreignInner")
    z = ET.SubElement(d, q("zeroOrMore"))
    ch = ET.SubElement(z, q("choice"))
    a = ET.SubElement(ch, q("attribute"))
    ET.SubElement(a, q("anyName"))
    ET.SubElement(ch, q("text"))
    fe = ET.SubElement(ch, q("element"))
    ET.SubElement(fe, q("anyName"))
    ET.SubElement(fe, q("ref")).set("name", "foreignInner")

    # the foreign-attribute wildcard: any attribute outside the no-namespace
    # and phyphox names, which the parsers never look at (editor:uuid ...)
    d = ET.SubElement(grammar, q("define"))
    d.set("name", "foreignAttrs")
    z = ET.SubElement(d, q("zeroOrMore"))
    a = ET.SubElement(z, q("attribute"))
    any_name = ET.SubElement(a, q("anyName"))
    exc = ET.SubElement(any_name, q("except"))
    ET.SubElement(exc, q("nsName")).set("ns", "")
    ET.SubElement(exc, q("nsName")).set("ns", PHYPHOX_NS)
    ET.SubElement(exc, q("nsName")).set("ns", PHYPHOX_NS_ALT)
    ET.SubElement(a, q("text"))

    ET.indent(grammar)
    return ET.tostring(grammar, encoding="unicode", xml_declaration=False)


# ---------------------------------------------------------- rnc (compact) --

def rnc_string(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def rnc(defines, start_id):
    out = []

    def emit(node, indent):
        pad = "  " * indent
        if node.kind == "element":
            names = " | ".join(f"{n} | p:{n} | ps:{n}" for n in node.names)
            out.append(f"{pad}element {names} {{")
            join_parts(node.parts, indent + 1)
            out.append(f"{pad}}}")
        elif node.kind == "attribute":
            out.append(f"{pad}attribute {node.name} {{ {data_str(node.value)} }}")
        elif node.kind == "attribute_except":
            exc = " | ".join(f"local:{n}" for n in node.names)
            out.append(f"{pad}attribute local:* - ({exc})"
                       f" {{ {data_str(node.value)} }}")
        elif node.kind == "optional":
            emit(node.child, indent)
            out[-1] += "?"
        elif node.kind == "zeroOrMore":
            emit(node.child, indent)
            out[-1] += "*"
        elif node.kind == "oneOrMore":
            emit(node.child, indent)
            out[-1] += "+"
        elif node.kind == "interleave":
            # RNC forbids mixing "," and "&" at one level: group the
            # interleave in parentheses.
            out.append(f"{pad}(")
            join_parts(node.parts, indent + 1, sep=" &")
            out.append(f"{pad})")
        elif node.kind == "choice":
            out.append(f"{pad}(")
            join_parts(node.parts, indent + 1, sep=" |")
            out.append(f"{pad})")
        elif node.kind == "ref":
            out.append(f"{pad}{node.name}")
        elif node.kind == "text":
            out.append(f"{pad}text")
        elif node.kind == "empty":
            out.append(f"{pad}empty")
        elif node.kind == "data":
            out.append(f"{pad}{data_str(node)}")
        else:
            raise ValueError(node.kind)

    def data_str(node):
        if node.kind == "ref":
            return node.name
        if node.kind == "text":
            return "text"
        if node.kind == "choice":
            return " | ".join(data_str(p) for p in node.parts)
        if getattr(node, "xsd", None):
            return f"xsd:{node.xsd}"
        return f"xsd:string {{ pattern = {rnc_string(node.pattern)} }}"

    def join_parts(parts, indent, sep=","):
        for i, p in enumerate(parts):
            emit(p, indent)
            if i < len(parts) - 1:
                out[-1] += sep

    out.append("# Generated from spec/*.yml by tools/generate_validators.py.")
    out.append("# Do not edit; see the validators page of the documentation")
    out.append("# for scope and limitations.")
    out.append("")
    out.append(f'namespace p = "{PHYPHOX_NS}"')
    out.append(f'namespace ps = "{PHYPHOX_NS_ALT}"')
    out.append('namespace local = ""')
    out.append('datatypes xsd = "http://www.w3.org/2001/XMLSchema-datatypes"')
    out.append("")
    out.append(f"start = {start_id}")
    for did, node in defines.items():
        out.append("")
        out.append(f"{did} =")
        emit(node, 1)
    out.append("")
    out.append("foreign =")
    out.append("  element * - (local:* | p:* | ps:*) { foreignInner }")
    out.append("foreignInner =")
    out.append("  (attribute * { text } | text | element * { foreignInner })*")
    out.append("foreignAttrs =")
    out.append("  attribute * - (local:* | p:* | ps:*) { text }*")
    out.append("")
    return "\n".join(out) + "\n"


# -------------------------------------------------------------- schematron --

SCH_NS = "http://purl.oclc.org/dsdl/schematron"


def version_ok(since):
    """XPath 1.0 test: root version attribute >= since (major.minor)."""
    m, n = str(since).split(".")
    return ("(number(substring-before(/*/@version, '.')) > {m} or "
            "(number(substring-before(/*/@version, '.')) = {m} and "
            "number(substring-after(/*/@version, '.')) >= {n}))"
            ).format(m=m, n=n)


def ln(name):
    return f"*[local-name()='{name}']"


def schematron(els, common):
    import xml.etree.ElementTree as ET
    ET.register_namespace("sch", SCH_NS)

    def q(tag):
        return f"{{{SCH_NS}}}{tag}"

    root = ET.Element(q("schema"))
    root.set("queryBinding", "xslt")
    t = ET.SubElement(root, q("title"))
    t.text = ("phyphox file format - rules the RELAX NG grammar cannot "
              "express. Generated from spec/*.yml by "
              "tools/generate_validators.py.")

    def pattern(pid):
        p = ET.SubElement(root, q("pattern"))
        p.set("id", pid)
        return p

    def rule(p, context):
        r = ET.SubElement(p, q("rule"))
        r.set("context", context)
        return r

    def assert_(r, test, text, warning=False):
        a = ET.SubElement(r, q("assert"))
        a.set("test", test)
        if warning:
            a.set("role", "warning")
        a.text = text

    containers = (f"//{ln('data-containers')}/{ln('container')}"
                  f"[normalize-space(.) = normalize-space(current())]")
    buffer_ok = f"normalize-space(.) = '' or {containers}"

    # --- data-container references resolve -------------------------------
    p = pattern("buffer-references")
    type_is = lambda v: ("translate(@type,'ABCDEFGHIJKLMNOPQRSTUVWXYZ',"
                         f"'abcdefghijklmnopqrstuvwxyz') = '{v}'")
    skip_value = f"(@type and ({type_is('value')} or {type_is('empty')}))"
    ref_text = "This text must name a data container declared in data-containers."

    r = rule(p, f"/{ln('phyphox')}/{ln('analysis')}/*/"
                f"*[local-name()='input' or local-name()='output']")
    assert_(r, f"{skip_value} or {buffer_ok}", ref_text)

    r = rule(p, f"/{ln('phyphox')}/{ln('export')}/{ln('set')}/{ln('data')}")
    assert_(r, buffer_ok, ref_text)

    r = rule(p, f"/{ln('phyphox')}/{ln('views')}/{ln('view')}/*/"
                f"*[local-name()='input' or local-name()='output']")
    assert_(r, f"{skip_value} or {buffer_ok}", ref_text)

    r = rule(p, f"/{ln('phyphox')}/{ln('input')}/*/{ln('output')}")
    assert_(r, buffer_ok, ref_text)

    r = rule(p, f"/{ln('phyphox')}/{ln('output')}/{ln('audio')}"
                f"//{ln('input')}")
    assert_(r, f"{skip_value} or {buffer_ok}", ref_text)

    r = rule(p, f"/{ln('phyphox')}/{ln('output')}/{ln('flashlight')}"
                f"/{ln('input')}")
    assert_(r, f"{skip_value} or {buffer_ok}", ref_text)

    r = rule(p, f"/{ln('phyphox')}/{ln('network')}/{ln('connection')}"
                f"/{ln('send')}")
    assert_(r, f"(@type and not({type_is('buffer')})) or {buffer_ok}",
            ref_text)
    r = rule(p, f"/{ln('phyphox')}/{ln('network')}/{ln('connection')}"
                f"/{ln('receive')}")
    assert_(r, buffer_ok, ref_text)

    # --- container names are unique --------------------------------------
    p = pattern("container-uniqueness")
    r = rule(p, f"/{ln('phyphox')}/{ln('data-containers')}/{ln('container')}")
    assert_(r, f"count(../{ln('container')}[normalize-space(.) = "
               "normalize-space(current())]) = 1",
            "Data container names must be unique.")

    # --- root metadata appears at most once ------------------------------
    # The grammar cannot express this: the root's children are deliberately
    # folded into one repeated choice to sidestep libxml2's interleave
    # blowup. Rule duplicate-metadata-last-wins (spec/rules.yml): apps
    # tolerate a legacy duplicate - the last occurrence wins - but nothing
    # may write one, so a duplicate is an authoring error.
    p = pattern("root-metadata-once")
    for name in ("title", "state-title", "category", "icon", "color",
                 "description"):
        r = rule(p, f"/{ln('phyphox')}/{ln(name)}")
        assert_(r, f"count(../{ln(name)}) = 1",
                f"The {name} element may appear at most once; apps "
                "tolerate a legacy duplicate (the last occurrence wins) "
                "but nothing may write one.")

    # --- graph dataset pairing (decided and amended 2026-08-20) ----------
    p = pattern("graph-dataset-pairing")
    ax = lambda v: ("translate(@axis,'ABCDEFGHIJKLMNOPQRSTUVWXYZ',"
                    f"'abcdefghijklmnopqrstuvwxyz') = '{v}'")
    gin = f"{ln('input')}"
    nx = f"count({gin}[{ax('x')}])"
    ny = f"count({gin}[{ax('y')}])"
    r = rule(p, f"/{ln('phyphox')}/{ln('views')}/{ln('view')}/{ln('graph')}")
    assert_(r, f"{nx} <= {ny}",
            "More x inputs than y inputs: some x input is used by no y "
            "input, which is an error.")
    # with unequal counts, a trailing or shadowed x is unused - an error
    trailing = (f"{gin}[{ax('x')}][not(following-sibling::"
                f"{ln('input')}[{ax('y')}])]")
    shadowed = (f"{gin}[{ax('x')}][following-sibling::{ln('input')}"
                f"[{ax('x')} or {ax('y')}][1]"
                f"[translate(@axis,'ABCDEFGHIJKLMNOPQRSTUVWXYZ',"
                f"'abcdefghijklmnopqrstuvwxyz') = 'x']]")
    assert_(r, f"{nx} = {ny} or not({trailing})",
            "With unequal x and y counts, an x input not followed by any y "
            "input is unused - an error.")
    assert_(r, f"{nx} = {ny} or not({shadowed})",
            "With unequal x and y counts, an x input shadowed by a later x "
            "before any y consumed it is unused - an error.")

    # --- mapColor[N]: the wildcard the grammar admits, pinned down -------
    graph = [v for k, v in els.items() if k == ("views", "view", "graph")][0]
    known = [a["name"] for a in graph.get("attributes") or []
             if not a.get("name_pattern")]
    known += [a["name"] for a in
              common.get("views", {}).get("view_element_attributes", [])]
    known_str = "|" + "|".join(known) + "|"
    p = pattern("mapcolor-names")
    r = rule(p, f"/{ln('phyphox')}/{ln('views')}/{ln('view')}/{ln('graph')}")
    bad = (f"@*[namespace-uri() = '' and "
           f"not(contains('{known_str}', concat('|', name(), '|'))) and "
           "not(starts-with(name(), 'mapColor') and "
           "substring-after(name(), 'mapColor') != '' and "
           "translate(substring-after(name(), 'mapColor'), "
           "'0123456789', '') = '' and "
           "not(starts-with(substring-after(name(), 'mapColor'), '0')))]")
    assert_(r, f"not({bad})",
            "The only dynamically numbered attributes on graph are "
            "mapColor1, mapColor2, ... - anything else is not part of the "
            "format.")

    # --- since gates (warnings: older apps will reject these files) ------
    p = pattern("version-gates")
    for (block, parent, name), el in sorted(els.items(),
                                            key=lambda kv: str(kv[0])):
        ctx = (f"{ln(parent)}/{ln(name)}" if parent else f"/{ln(name)}")
        gates = []
        el_since = el.get("since")
        if el_since and str(el_since) not in ("1.0",):
            gates.append((None, el_since))
        for a in el.get("attributes") or []:
            if a.get("since") and str(a["since"]) != "1.0":
                gates.append((a["name"], a["since"]))
        if parent == "analysis":
            for a in common.get("analysis", {}).get("module_attributes", []):
                if a.get("since") and str(a["since"]) != "1.0":
                    gates.append((a["name"], a["since"]))
        if parent == "view":
            for a in common.get("views", {}).get("view_element_attributes",
                                                 []):
                if a.get("since") and str(a["since"]) != "1.0":
                    gates.append((a["name"], a["since"]))
        if not gates:
            continue
        r = rule(p, ctx)
        for attr, since in gates:
            if attr is None:
                assert_(r, version_ok(since),
                        f"<{name}> needs file format {since} or later; this "
                        "file declares an older version.", warning=True)
            else:
                assert_(r, f"not(@{attr}) or {version_ok(since)}",
                        f"The {attr} attribute of <{name}> needs file format "
                        f"{since} or later; this file declares an older "
                        "version.", warning=True)

    import xml.etree.ElementTree as ET2
    ET2.indent(root)
    return ET2.tostring(root, encoding="unicode")


# ------------------------------------------------------------------ build --

def build():
    """Render the three artifacts; returns {filename: content}."""
    els, common, colors = load()
    VALUE_TYPES.clear()
    order = sorted(els, key=lambda k: (str(k[0]), str(k[1]), k[2]))
    defines = {define_id(k): element_pattern(els, common, colors, k)
               for k in order}
    for did, node in VALUE_TYPES.values():
        defines[did] = node
    start_id = define_id(("root", None, "phyphox"))
    return {
        "phyphox.rng": rng_xml(defines, start_id) + "\n",
        "phyphox.rnc": rnc(defines, start_id),
        "phyphox.sch": schematron(els, common) + "\n",
    }


def generate(out_dir=DEFAULT_OUT):
    """Write the artifacts into out_dir, touching only files whose content
    actually changed - mkdocs serve watches docs/, and an unconditional
    write on every build would retrigger the build forever."""
    os.makedirs(out_dir, exist_ok=True)
    written = []
    for fn, content in build().items():
        path = os.path.join(out_dir, fn)
        old = None
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                old = f.read()
        if old != content:
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            written.append(fn)
    return out_dir, written


if __name__ == "__main__":
    out, written = generate(sys.argv[1] if len(sys.argv) > 1 else DEFAULT_OUT)
    print(f"wrote {', '.join(written) if written else 'nothing (unchanged)'}"
          f" to {out}")
